builds:
#  AGENT
  - main: main.go
    binary: cio
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
# CLI
  - main: ./cio-cli/main.go
    binary: cio-cli
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archive:
  name_template: "{{ .ProjectName }}.{{ .Arch }}.{{ .Os }}"
  format: binary
release:
  prerelease: false
  name_template: "{{.ProjectName}}-v{{.Version}}"
