builds:
  - main: main.go
    binary: cio
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  name_template: "{{ .ProjectName }}.{{ .Arch }}.{{ .Os }}"
  format: binary
release:
  prerelease: true
  name_template: "{{.ProjectName}}-v{{.Version}}"
