// Copyright (c) 2017-2022 Ingram Micro Inc.

package api

const (
	PathAuditEvents       = "/audit/events"
	PathAuditSystemEvents = "/audit/system_events"

	PathBlueprintAttachment             = "/blueprint/attachments/%s"
	PathBlueprintAttachmentUploaded     = "/blueprint/attachments/%s/uploaded"
	PathBlueprintCookbookVersion        = "/blueprint/cookbook_versions/%s"
	PathBlueprintCookbookVersionProcess = "/blueprint/cookbook_versions/%s/process"
	PathBlueprintCookbookVersions       = "/blueprint/cookbook_versions"
	PathBlueprintScript                 = "/blueprint/scripts/%s"
	PathBlueprintScriptAttachments      = "/blueprint/scripts/%s/attachments"
	PathBlueprintScripts                = "/blueprint/scripts"
	PathBlueprintTemplate               = "/blueprint/templates/%s"
	PathBlueprintTemplateCompile        = "/blueprint/templates/%s/compile"
	PathBlueprintTemplates              = "/blueprint/templates"
	PathBlueprintTemplateScript         = "/blueprint/templates/%s/scripts/%s"
	PathBlueprintTemplateScripts        = "/blueprint/templates/%s/scripts"
	PathBlueprintTemplateScriptsReorder = "/blueprint/templates/%s/scripts/reorder"
	PathBlueprintTemplateScriptsType    = "/blueprint/templates/%s/scripts?type=%s"
	PathBlueprintTemplateServers        = "/blueprint/templates/%s/servers"

	PathBrownfieldCloudAccountImportFloatingIPs        = "/brownfield/cloud_accounts/%s/import_floating_ips"
	PathBrownfieldCloudAccountImportKubernetesClusters = "/brownfield/cloud_accounts/%s/import_kubernetes_clusters"
	PathBrownfieldCloudAccountImportPolicies           = "/brownfield/cloud_accounts/%s/import_policies"
	PathBrownfieldCloudAccountImportServers            = "/brownfield/cloud_accounts/%s/import_servers"
	PathBrownfieldCloudAccountImportVolumes            = "/brownfield/cloud_accounts/%s/import_volumes"
	PathBrownfieldCloudAccountImportVpcs               = "/brownfield/cloud_accounts/%s/import_vpcs"
	PathBrownfieldCloudAccount                         = "/brownfield/cloud_accounts/%s"
	PathBrownfieldCloudAccounts                        = "/brownfield/cloud_accounts"

	PathCloudCloudProviderClusterPlans       = "/cloud/cloud_providers/%s/cluster_plans"
	PathCloudCloudProviderLoadBalancerPlans  = "/cloud/cloud_providers/%s/load_balancer_plans"
	PathCloudCloudProviders                  = "/cloud/cloud_providers"
	PathCloudCloudProviderServerPlansByRealm = "/cloud/cloud_providers/%s/server_plans?realm_id=%s"
	PathCloudCloudProviderStoragePlans       = "/cloud/cloud_providers/%s/storage_plans"
	PathCloudGenericImages                   = "/cloud/generic_images"
	PathCloudProviderRealms                  = "/cloud/cloud_providers/%s/realms"
	PathCloudRealm                           = "/cloud/realms/%s"
	PathCloudRealmNodePoolPlans              = "/cloud/realms/%s/node_pool_plans"
	PathCloudServer                          = "/cloud/servers/%s"
	PathCloudServerArray                     = "/cloud/server_arrays/%s"
	PathCloudServerArrayBoot                 = "/cloud/server_arrays/%s/boot"
	PathCloudServerArrayEmpty                = "/cloud/server_arrays/%s/empty"
	PathCloudServerArrays                    = "/cloud/server_arrays"
	PathCloudServerArrayServers              = "/cloud/server_arrays/%s/servers"
	PathCloudServerArrayShutdown             = "/cloud/server_arrays/%s/shutdown"
	PathCloudServerBoot                      = "/cloud/servers/%s/boot"
	PathCloudServerEvents                    = "/cloud/servers/%s/events"
	PathCloudServerFloatingIps               = "/cloud/servers/%s/floating_ips"
	PathCloudServerOperationalScriptExecute  = "/cloud/servers/%s/operational_scripts/%s/execute"
	PathCloudServerOperationalScripts        = "/cloud/servers/%s/operational_scripts"
	PathCloudServerOverride                  = "/cloud/servers/%s/override"
	PathCloudServerPlan                      = "/cloud/server_plans/%s"
	PathCloudServerReboot                    = "/cloud/servers/%s/reboot"
	PathCloudServers                         = "/cloud/servers"
	PathCloudServerShutdown                  = "/cloud/servers/%s/shutdown"
	PathCloudServerVolumes                   = "/cloud/servers/%s/volumes"
	PathCloudSshProfile                      = "/cloud/ssh_profiles/%s"
	PathCloudSshProfiles                     = "/cloud/ssh_profiles"

	PathCseDeployment          = "/cse/deployments/%s"
	PathCseDeployments         = "/cse/deployments"
	PathCseTemplate            = "/cse/templates/%s"
	PathCseTemplateDeployments = "/cse/templates/%s/deployments"
	PathCseTemplates           = "/cse/templates"

	PathKubernetesCluster          = "/kubernetes/clusters/%s"
	PathKubernetesClusterDiscard   = "/kubernetes/clusters/%s/discard"
	PathKubernetesClusterNodePools = "/kubernetes/clusters/%s/node_pools"
	PathKubernetesClusterPlan      = "/kubernetes/cluster_plans/%s"
	PathKubernetesClusterRetry     = "/kubernetes/clusters/%s/retry"
	PathKubernetesClusters         = "/kubernetes/clusters"
	PathKubernetesNodePool         = "/kubernetes/node_pools/%s"
	PathKubernetesNodePoolPlan     = "/kubernetes/node_pool_plans/%s"
	PathKubernetesNodePoolRetry    = "/kubernetes/node_pools/%s/retry"

	PathLabelResource  = "/labels/%s/resources/%s/%s"
	PathLabelResources = "/labels/%s/resources"
	PathLabels         = "/labels"

	PathNetworkDnsDomain                = "/network/dns/domains/%s"
	PathNetworkDnsDomainRecords         = "/network/dns/domains/%s/records"
	PathNetworkDnsDomainRetry           = "/network/dns/domains/%s/retry"
	PathNetworkDnsDomains               = "/network/dns/domains"
	PathNetworkDnsRecord                = "/network/dns/records/%s"
	PathNetworkDnsRecordRetry           = "/network/dns/records/%s/retry"
	PathNetworkFirewallProfile          = "/network/firewall_profiles/%s"
	PathNetworkFirewallProfiles         = "/network/firewall_profiles"
	PathNetworkFloatingIp               = "/network/floating_ips/%s"
	PathNetworkFloatingIpAttachedServer = "/network/floating_ips/%s/attached_server"
	PathNetworkFloatingIpDiscard        = "/network/floating_ips/%s/discard"
	PathNetworkFloatingIps              = "/network/floating_ips"
	PathNetworkListener                 = "/network/listeners/%s"
	PathNetworkListenerRetry            = "/network/listeners/%s/retry"
	PathNetworkListenerRule             = "/network/listeners/%s/rules/%s"
	PathNetworkListenerRules            = "/network/listeners/%s/rules"
	PathNetworkLoadBalancer             = "/network/load_balancers/%s"
	PathNetworkLoadBalancerCertificate  = "/network/load_balancers/%s/certificates/%s"
	PathNetworkLoadBalancerCertificates = "/network/load_balancers/%s/certificates"
	PathNetworkLoadBalancerListeners    = "/network/load_balancers/%s/listeners"
	PathNetworkLoadBalancerPlan         = "/network/load_balancer_plans/%s"
	PathNetworkLoadBalancerRetry        = "/network/load_balancers/%s/retry"
	PathNetworkLoadBalancers            = "/network/load_balancers"
	PathNetworkLoadBalancerTargetGroups = "/network/load_balancers/%s/target_groups"
	PathNetworkSubnet                   = "/network/subnets/%s"
	PathNetworkSubnetServerArrays       = "/network/subnets/%s/server_arrays"
	PathNetworkSubnetServers            = "/network/subnets/%s/servers"
	PathNetworkTargetGroup              = "/network/target_groups/%s"
	PathNetworkTargetGroupRetry         = "/network/target_groups/%s/retry"
	PathNetworkTargetGroupTarget        = "/network/target_groups/%s/targets/%s/%s"
	PathNetworkTargetGroupTargets       = "/network/target_groups/%s/targets"
	PathNetworkVpc                      = "/network/vpcs/%s"
	PathNetworkVpcDiscard               = "/network/vpcs/%s/discard"
	PathNetworkVpcs                     = "/network/vpcs"
	PathNetworkVpcSubnets               = "/network/vpcs/%s/subnets"
	PathNetworkVpcVpn                   = "/network/vpcs/%s/vpn"
	PathNetworkVpcVpnPlans              = "/network/vpcs/%s/vpn_plans"

	PathPluginsToscaCat                     = "/plugins/tosca/cats/%s"
	PathPluginsToscaCatDeploymentTask       = "/plugins/tosca/cats/%s/deployment_tasks/%s"
	PathPluginsToscaCatDeploymentTasks      = "/plugins/tosca/cats/%s/deployment_tasks"
	PathPluginsToscaCatParseMetadata        = "/plugins/tosca/cats/%s/parse_metadata"
	PathPluginsToscaCats                    = "/plugins/tosca/cats"
	PathPluginsToscaDeployment              = "/plugins/tosca/deployments/%s"
	PathPluginsToscaTemporaryArchiveExport  = "/plugins/tosca/temporary_archives/%s/export"
	PathPluginsToscaTemporaryArchiveImport  = "/plugins/tosca/temporary_archives/%s/import"
	PathPluginsToscaTemporaryArchives       = "/plugins/tosca/temporary_archives"
	PathPluginsToscaTemporaryArchivesExport = "/plugins/tosca/temporary_archives/export"

	PathPolicyAssignment            = "/policy/assignments/%s"
	PathPolicyDefinition            = "/policy/definitions/%s"
	PathPolicyDefinitionAssignments = "/policy/definitions/%s/assignments"
	PathPolicyDefinitions           = "/policy/definitions"

	PathSettingsCloudAccount                  = "/settings/cloud_accounts/%s"
	PathSettingsCloudAccountPolicyAssignments = "/settings/cloud_accounts/%s/policy_assignments"
	PathSettingsCloudAccounts                 = "/settings/cloud_accounts"

	PathStoragePlan                 = "/storage/plans/%s"
	PathStorageVolume               = "/storage/volumes/%s"
	PathStorageVolumeAttachedServer = "/storage/volumes/%s/attached_server"
	PathStorageVolumeDiscard        = "/storage/volumes/%s/discard"
	PathStorageVolumes              = "/storage/volumes"

	PathWizardAppDeploy      = "/wizard/apps/%s/deploy"
	PathWizardApps           = "/wizard/apps"
	PathWizardCloudProviders = "/wizard/cloud_providers?app_id=%s&location_id=%s"
	PathWizardLocations      = "/wizard/locations"
	PathWizardServerPlans    = "/wizard/server_plans?app_id=%s&location_id=%s&cloud_provider_id=%s"
)

// ClientAPI web service manager
type ClientAPI struct {
	HTTPClient
}
